server:
  port: 8888

minio:
  endpoint: http://172.26.192.208:9000
#  endpoint: http://localhost:9000
  bucket-name: movie
  access-key: minioadmin
  secret-key: minioadmin
  use-proxy-url: true
  proxy-base-url: http://127.0.0.1:8888

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 55MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 60s
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_UUID
      #schema: classpath:/sql/schema.sql
  type-aliases-package: com.movie.api.model.entity